name: nifty-dev
channels:
  - conda-forge
dependencies:
  - python 3.12
  - numpy
  - xtensor >=0.25,<0.26
  - xtensor-python >=0.27,<0.28
  - libboost-devel
  - libvigra
  # Vigra Numpy is used at link time too
  - vigra
  - z5py >=2.0.11
  # build dependencies needed for z5
  - nlohmann_json
  - blosc
  - bzip2
  - zlib
