package:
  name: nifty
  version: v1.0.7


source:
  path: ..


build:
  number: 100


requirements:
  build:
    # conda compilers cause issues ...
    # - {{ compiler('cxx') }}
    # - cmake
    - xtensor
    - xtensor-python
    - nlohmann_json

  host:
    - python
    - boost-cpp >=1.63
    - hdf5 >=1.10
    - numpy >=1.15
    - blosc
    - z5py >=2.0.5
    - vigra
    - bzip2
    - zlib

  run:
    - python
    - scikit-image
    - vigra
    # - hdf5 >=1.10
    # - numpy >=1.15
    # - blosc
    # - bzip2
    # - zlib


test:
  imports:
    - nifty


about:
  home: https://github.com/DerThorsten/nifty
  license: MIT
  summary: Graph-based segmentation algorithms
