#!/bin/bash

cmake . \
    -DWITHIN_TRAVIS=ON \
    -DWITH_QPBO=OFF \
    -DWITH_HDF5=ON \
    -DWITH_Z5=ON \
    -DWITH_ZLIB=ON \
    -DWITH_BLOSC=ON \
    -DWITH_GLPK=OFF \
    -DWITH_CPLEX=OFF \
    -DWITH_GUROBI=OFF \
    -DBUILD_CPP_TEST=OFF \
    -DCMAKE_PREFIX_PATH="$CONDA_PREFIX" \
    -DPython_EXECUTABLE="${CONDA_PREFIX}/bin/python" \
    -DCMAKE_INSTALL_PREFIX="$CONDA_PREFIX" \
    -DBUILD_NIFTY_PYTHON=ON
make -j 4
make install
