name: C++ and python bindings CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest]
            python-version: [3.7]
    name: Test ${{ matrix.os }} - ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1
      with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
    - name: configure
      run: ./.github/workflows/configure.sh
    - name: make
      run: make install
    - name: test
      run: ./.github/workflows/test.sh
